[package]
name = "teknify"
version = "0.2.0"
authors = ["Adam <sector-f@users.noreply.github.com>"]

[dependencies]
clap = "2.5.*"
hyper = "0.8"
multipart = "0.7.0"
num_cpus = "0.2"
serde_json = "0.7"
threadpool = "1.3.*"
url = "1.1.*"
